//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParaTech_Energy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int CID { get; set; }
        public string ClientName { get; set; }
        public string CliDescription { get; set; }
        public string ClientLogo { get; set; }
        public string CliProjName { get; set; }
    }
}
