//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParaTech_Energy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solution
    {
        public int ID { get; set; }
        public string PageName { get; set; }
        public string PageTitle { get; set; }
        public string PageImage { get; set; }
        public string PageDes { get; set; }
        public bool NewPage { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
    }
}
